### ISSUE TITLE
Feature Request: Hide non translatable fields (WMPL)

### ISSUE THREAD

**Issue by igaster** [rilwis/meta-box#1058]
Hi! I am using WPML to trasnlate my child theme.

I wan't some fields to be shared among translations, (WMPL setting for field is "Copy" instead of "Translate")

Current Behavior: These fields are showing in all translations, but can be update only from the default translation. If the user tries to edit a version on the translation then it is not saved.

Proposed Behavior: either a) Show field as read only on trasnlations and enable editing on default language. or B) Hide them completely when apropriate

I suppose that the same problem occurs when a field is set as "Do nothing" instead of "Copy" (Haven't test it)

Cheers!

**Comment by rilwis** [comment]
I went with the 1st option: Set the fields that are copied disabled for editing.

For fields that are set to "Do not translate", hide them completely.

But to hide "Do not translate" field, users must click Apply button to tell WPML about that (so it saves the configuration). Otherwise, fields are showing up.
