### ISSUE TITLE
Display Fields in Frontend

### ISSUE THREAD

**Issue by Supermarky** [rilwis/meta-box#1098]
Excuse me, I´m not a developer, but how can I display the stuff that I ve found here in DEMO.PHP on frontend? What PHP-Code I have to use? I have no idea and nothing worked.

Thanks for helping!

**Comment by goodyis** [comment]
I know I'm not 'with' meta-box; however without seeing your demo.php, not sure how much help anyone can give you. However, if you have setup every thing correctly on the backend - including the fields in your functions.php or somewhere else then you most likely will have to call the field in your template or in your case on demo.php. 

Meaning, you will need to either store the value and then display it, or just display it if you are sure you don't need to check it exists first. Take a look below, and go here [https://metabox.io/docs/get-meta-value/]

Note: $field_id refers to the id given your meta-field, if no id defaults to name

Inside a wp-loop and check if it exists:

`<?php 
$myStoredValue = rwmb_meta($field_id);
if(isset($myStoredValue) {
   echo $myStoredValue; }
else { //stored value empty or not working so do nothing }  `

Outside a wp-loop and not checking if it exists:
 - please refer to link above, you could omit $args but because you are outside the loop you will need post id here

`<?php echo rwmb_meta( $field_id, $args, $post_id ); ?>`
