### ISSUE TITLE
Custom fields disappeared from Page and Post

### ISSUE THREAD

**Issue by timpowersdesign** [rilwis/meta-box#1157]
Since updating to 4.12.2 the fields have disappeared from the "Post" and "Page" edit pages. Content from the custom fields still display on the site, but I can't edit anything or add new fields.

**Comment by funkedgeek** [comment]
We need the code you are using to create the meta boxes, including the functions and the filter calls

**Comment by timpowersdesign** [comment]
All I've ever had to do is install the plugin, include the code below in /yourtheme/functions.php and it worked. No other filters, functions etc. I wasn't aware there were other functions/filters etc. 

rwmb_meta( $field_id, $args = array(), $post_id = null );

This is what I have within the WP Loop

<div class="<?php echo rwmb_meta( 'page_wrapper' ); ?>">

Weirdly, ACF Pro has picked up the content I had in the Custom Fields after creating fields with the same names. Note, I've never had an issue with ACF Pro and Meta Box Custom Fields till this latest iteration of Meta Box.

**Comment by funkedgeek** [comment]
But how are you creating the fields?

**Comment by timpowersdesign** [comment]
Sorry, the previous comment stripped out my code - which is understandable. Please see previous comment. 

To actually make the fields, it would appear in the page/post editor in the backend of WordPress - but this has disappeared.
Are there other ways to do this, because I don't understand why you'd need to ask this if the plugin works the same for everyone...

**Comment by funkedgeek** [comment]
I think you are misunderstanding the use of the plugin.  The Meta Box plugin is designed to create meta boxes with fields that you can populate, which is then saved as meta data.  Sounds like you aren't actually making meta boxes and are instead using WordPress's custom field box, which is not how this plugin is intended to be used.  Please see the getting started mage of our plugin: https://metabox.io/docs/getting-started/

**Comment by timpowersdesign** [comment]
It appears this plugin has come a long way since I first installed it then. Still doesn't explain why since the update, the fields have disappeared (see attached image)
![customfields](https://user-images.githubusercontent.com/25511986/28881665-c48ff83e-77a0-11e7-993a-87c4caba64a5.JPG)

**Comment by timpowersdesign** [comment]
Don't close this thread, you haven't helped to solve my issue.

**Comment by funkedgeek** [comment]
That is the custom fields meta box that is built into WordPress.  Our plugin has no control over that.

**Comment by timpowersdesign** [comment]
It did when I installed the plugin, otherwise I wouldn't have installed it.

**Comment by funkedgeek** [comment]
In a posts edit page, on the top of the page there is a button called `Screen Options`.  Click on that and it will give you the option to re-enable the `Custom Fields` meta box.

**Comment by timpowersdesign** [comment]
It's not there.

I've tried looking in Screen Options, reinstalling the plugin, reinstalling 4.12.1 etc. etc.

After doing a quick test it appears the issue may be with ACF Pro. Such a shame as I've had both plugins working together previously, but I'll just have to revert to using ACF Pro for the foreseeable future.

**Comment by funkedgeek** [comment]
So just to verify, you used code to create meta boxes in fields using our plugin?  I'm still confused to how you are using this.

**Comment by timpowersdesign** [comment]
After looking at another site which has updated to 4.12.2 perfectly fine, I too am very confused.

I still use `<?php echo rwmb_meta( 'book_code' ); ?> <?php the_title();?>` but I have at some point commented out rwmb_meta( $field_id, $args = array(), $post_id = null ); and it still all works absolutely fine.

**Comment by timpowersdesign** [comment]
If I deactivate Meta Box, everything breaks.

**Comment by funkedgeek** [comment]
I'm still confused.  If you are using the plugin correctly, you would have created some custom code to create the meta box.  I need that code so I can see what the problem is.  If you never created such code, then I'm not sure how you are using our plugin.

**Comment by timpowersdesign** [comment]
I've given you all the code I've ever had to use since installing your plugin a couple of years ago. I may not be using it as you want me to, but however it is I've done it, it works! 

As I said, the original issue was caused by Advanced Custom Fields. must have been an update you and/or they have made which has caused the original Custom Fields box to disappear.

Either way, my main concern was updating to 4.12.2 on a site that relies heavily on Custom Fields, but it has updated with no issues, and I'm still able to edit using the Custom Fields box as pictured above.

**Comment by funkedgeek** [comment]
I would then suggest that you use the plugin as intended in create your own fields.  The link I gave you above should give you a start.  Since we can't really provide you support if you aren't even using the plugin as intended, this ticket is staying closed.

**Comment by timpowersdesign** [comment]
I don't need support anymore, I found the issue (and ergo solution) myself, it was ACF Pro that was causing the Custom Fields box to disappear. But as ACF Pro can find the data I entered using the Custom Fields box, I will use that for now on with sites that use ACF Pro. 

The issue doesn't occur on sites that don't also have ACF Pro in any capacity, so I will continue to use Meta Box - incorrectly as you keep implying.

**Comment by rilwis** [comment]
Hi Tim,

Just looked into this thread and I see you have some problems using ACF and Meta Box. So let me try to clarify things and hope that helps you to use the plugins better.

Firstly, the custom fields meta box you see when editing posts or pages is created by WordPress, not by any plugins ACF or Meta Box. You can see the explanation on WordPress Codex [here](https://codex.wordpress.org/Custom_Fields).

Secondly, as that meta box is a WordPress's default, any plugin that tries to hide it is doing wrong. And as you found out that ACF causes this problem, ACF does it wrong.

3rd, both Meta Box and ACF is aimed to help users/developers to create meta boxes with custom fields. The meta boxes created by these plugins (let's call them A) are **different** than the "Custom Fields" meta box from WordPress that we talked above (let's call them B). B will show all field values in A. And because of this, I guess it confused you, because you thought you used the plugins to create B. But you actually created A.

4th, the way you **show** value in the frontend has nothing related with the backend. Meaning that just gets the value stored in the database. As ACF and Meta Box already saves data in the database, you can get it without any problem.

Finally, as I see you already use Meta Box helper function to get meta value, I'd suggest you keep using it for the backend. So you don't rely on the default "Custom Fields" meta box anymore. And you will create a better interface for entering the data.

If you want to do so, please [follow this guide](https://metabox.io/docs/getting-started/) to get started.

Thanks
Anh

**Comment by jhard** [comment]
Should anybody else run into this, you can make acf not remove the metabox by changing their settings with a filter:

`add_filter("acf/settings/remove_wp_meta_box", function($val) {
    return false;
 } );`

**Comment by rilwis** [comment]
@jhard Probably this is shorter:

```
add_filter("acf/settings/remove_wp_meta_box", '__return_false' );
```
