### ISSUE TITLE
File deletion not working

### ISSUE THREAD

**Issue by martinsookael** [rilwis/meta-box#571]
Thank you for the plug-in! 

I looked through the open and closed issues for deleting files but did not find the exact same problem. 

Description: 
1) adding files works.
2) deleting files from backend removes them from backend, but
3) if I query for the files via JSON-API (https://wordpress.org/plugins/json-api/), it still serves me the files + they are also present in wp_posts & wp_postmeta.
4) If I add another file to the place where I deleted one the new file just gets appended to the list of files associated with the post.

Here's my code: 

```
add_filter( 'rwmb_meta_boxes', 'register_meta_boxes' );

function register_meta_boxes( $meta_boxes )
{
    $prefix = 'rw_';
    $meta_boxes[] = array(
        'id'       => 'courses',
        'title'    => 'Course metadata',
        'pages'    => array( 'post', 'page', 'course' ),
        'context'  => 'normal',
        'priority' => 'high',
        'fields' => array(
            // There's some more fields here
            array(
                'name'  => 'Photo 1',
                'id'    => $prefix . 'ph1',
                'type'  => 'image'
            ),
            array(
                'name'  => 'Photo 2',
                'id'    => $prefix . 'ph2',
                'type'  => 'image'
            ),
            array(
                'name'  => 'Photo 3',
                'id'    => $prefix . 'ph3',
                'type'  => 'image'
            ),
            array(
                'name'  => 'Photo 4',
                'id'    => $prefix . 'ph4',
                'type'  => 'image'
            ),
        )
    );
    return $meta_boxes;
}
```

**Comment by rilwis** [comment]
Hi,

For `file` and any image fields, we have an additional parameter `force_delete` which force to delete files from WP Media Library. If this param is `true` then when deleting file in WP admin, file will be deleted (physically). Otherwise, it's only remove from post meta and available in Media Library. Default is `false`.

The reason default is `false` is because the file maybe is used in many posts. If we remove it from 1 post meta, it might affect to other posts' meta as well and gives us unexpected result.

**Comment by martinsookael** [comment]
Thank you for the reply and the explanation. This worked. :+1:
