### ISSUE TITLE
Get fields value and display in the fronted

### ISSUE THREAD

**Issue by stefkey** [rilwis/meta-box#616]
Hello,

its very strange, or?
Simple work:
In my functions.php at second line:
//METABOX
include 'text.php';

I uses the text.php from demo-folder

In my single.php there is:
<?php echo 'Testtext' ?>
<?php echo rwmb_meta( 'text', 'type=text' ); ?>

In frontend I see the word Testtext but after this there is only "Array"
In backend I have write Testbox in the field from the PlugIn!

What's wrong? I don't unterstand it :-(

**Comment by wgdes** [comment]
I think your problem is probably that text fields are inherently clone-able -- so pulling the data like that would return an array.

If your field isn't clone-able, Try this instead:

$text = rwmb_meta( 'text', 'type=text' );
echo reset($text);

OR try this:

foreach($text = rwmb_meta( 'text', 'type=text' )){
  echo $text;
}
