### ISSUE TITLE
getting Fatal error

### ISSUE THREAD

**Issue by ah-polash** [rilwis/meta-box#630]
Why I m getting 
{{ Fatal error: Call to undefined function wp_json_encode() in C:\xampp\htdocs\skype\wp-content\plugins\rondell-carousel\meta-box\inc\fields\slider.php on line 41}}

after activating the plugin
see here  https://www.dropbox.com/s/mattse4bsm348qa/Snap%202015-07-05%20at%2009.09.15.png?dl=0

**Comment by rilwis** [comment]
I see you're using Rondell Carousel which includes meta box inside. I think the problem is how the plugin loaded Meta Box. It would be impossible to fix this unless we know the plugin's code.

However, I would recommend using Meta Box as a separated plugin instead of directly bundled it like this. See the reasons [here](https://metabox.io/docs/include-meta-box-plugin-themes/).

**Comment by rilwis** [comment]
FYI, this problem is caused by outdated version of WordPress. Updating WordPress to latest version solves the problem.
