### ISSUE TITLE
Issue about order/priority

### ISSUE THREAD

**Issue by stephen105** [rilwis/meta-box#642]
Hi,
I'm using Meta-box and Visual Composer for my site. Currently, Visual Composer load after Meta-box, i want Meta Boxes load after Visual Composer box - please see my screenshot to understand: http://take.ms/fHaCz
They have same priority is high(i dont want change priority). Please suggest me a solution.

Thanks!

**Comment by rilwis** [comment]
Did you try `'context' => 'advanced'` and `'prority' => 'low'` for meta box?

**Comment by stephen105** [comment]
I've tried almost values for 2 options 'context' and 'prority' but no luck :) . With your suggest my metabox load after VC but it load after some boxes(Discussion, Revolution Slider Options, Author, ... )
I want it load after VC and before some boxes above. Do you have use VC and have this issue?

Best Regards!

**Comment by rilwis** [comment]
In my test, the Visual Composer editor is loaded **before** meta boxes added by the Meta Box plugin.

I think the problem comes from **manual reorder** meta boxes. Maybe you already moved meta boxes before, so WordPress remembers their positions. When VC is activated, its meta box is loaded after all sorted meta boxes.

You can reset the saved order by removing the `meta-box-order-$post_type` user meta in `usermeta` table, like this:

http://prntscr.com/8rmdpp

**Comment by stephen105** [comment]
My issue resolved, Thanks for your solution :+1:
