### ISSUE TITLE
Taxonomy Field Issue

### ISSUE THREAD

**Issue by krishna19** [rilwis/meta-box#646]
Hi,

Whenever i use two taxonomy field type, there was a occur. For first taxomony field i select CAT 2 and i select CAT 1 for second taxonomy field. After update, the first taxonomy field was replaced with the option select in field 2. Please check the video

https://www.youtube.com/watch?v=l_jjYv4r7Qg

Thanks

**Comment by funkedgeek** [comment]
If those two fields are of the same taxonomy, then its supposed to work like that.  Try making two separate taxonomies.

**Comment by funkedgeek** [comment]
A longer explanation: the reason it acts this way is two fold.  Firstly, if those two selects are from the same taxonomy, the fields will be name the same.  The way HTML forms and the Meta Box code works, if two fields are named the same, the last one will be the one the code sees and therefore the one that gets saved.

Secondly, since those fields are using the same taxonomy, whatever terms are saved for that post will be displayed on both those fields when you reload.  So if you select `CAT 1` for that post, that is what will show up on both fields.

To prevent the problems you are having, either use 2 separate taxonomies, one for each meta box or switch to post meta.  Either way, you'll need to rework your code.  Let me know if you have any other questions, but I consider this ticket closed.
