### ISSUE TITLE
Wysiwyg validation

### ISSUE THREAD

**Issue by Sinusite** [rilwis/meta-box#669]
Hi,

<a href="https://metabox.io/docs/validation/" target="_blank">Validation </a> for WYSIWYG field doesn't work - OK for textarea type or if the WYSYWYG is on HTML mode...

Any idea ?

Thanks

**Comment by rilwis** [comment]
Validation module works for input fields only, due to the nature of the jQuery validation library. The WordPress editor (WYSIWYG field) is much more complicated and it has custom Javascript to manipulate its own value (get, set, update value in textarea when we type in the editor). I don't think it work for that :(

**Comment by Sinusite** [comment]
OK. I'm looking for a solution... i'll be back with this :-)
Thank you
