### ISSUE TITLE
fieldset_text issue when using clone

### ISSUE THREAD

**Issue by 0biWanKenobi** [rilwis/meta-box#706]
the html function receives a field with different id for every cloned fieldset, in the format `$fieldname_NUMBER` . It's like `$meta` has multiple values even with only one row, so the `show` function in `field.php` appends a `'_'.$index` to the metabox id. This causes quite the trouble when cloning, because every field except the first gets a wrong `name` and therefore is not saved to DB.

Much probably related, the html function expects to read field value from an array with structure `$meta[$row][$key]`. However this doesn't seem to work when there's only a single row, so I changed the code to read from `$meta[key]` as a stopgap solution. 

My guess is that there's something wrong with the `$meta` parameter that the html function receives, it should be an array with numeric indexes for each row, instead I get an array with the key=>value couples directly inside. 

My textfield metabox is declared as such:
```
// TEXT FIELD
			array(
				'id'      => "{$prefix}fieldset_text",
				'name'    => __( '', 'rw' ),
				'type'    => 'fieldset_text',
				// Number of rows
				'rows'    => 1,
				// Options: array of Label => key for text boxes
				// Note: key is used as key of array of values stored in the database
				// Number of options are not limited
				'options' => array(
					'nome'    => __( 'Nome', 'rw' ),
					'desc' => __( 'Descrizione', 'rw' ),
				),
				'clone' => true,
			),
```

**Comment by funkedgeek** [comment]
Actually, the logic changed slightly when we made field attributes more consistent: if the field is a clone, no ids are given, just the name.  It was a bit inconsistent before but made that the default rule when I added the attribute capabilities.  If you're on the latest version of the plugin, clone input fields should not have ids on them.

That being said, the reason its not saving has nothing to do with the id; it's because this field wasn't written taking cloning into account.  Don't understand why it has rows, as that is sorta interfering with the cloning process.  Going to look into rewriting this code.

**Comment by funkedgeek** [comment]
Re-looking at the code again and I'm not sure what the `row` argument for the field does. If I set to anything other than 1, it duplicates the fields but you can already do that with cloning.  I thinking about just pulling it.

Just added a commit that should fix your issue: https://github.com/rilwis/meta-box/commit/cff13e78e3aff9f3720f415c23c4074ee499e566.  Please update your code and test it out.

**Comment by 0biWanKenobi** [comment]
Thanks a lot for the fix, sir!
