### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by krishna19** [rilwis/meta-box#710]
What is the difference between Meta Box Conditional Logic, Meta Box Show Hide (JS) & Meta Box Include Exclude ?

**Comment by rilwis** [comment]
Hi, these are the main difference between them:

Meta Box Include Exclude: it hide meta boxes **by PHP**, meaning:

- Meta boxes are removed completely from the editing screen, no HTML markup is outputted at all
- Since meta boxes are removed completely --> there are no inputs at all --> there are no meta values are saved at all
- There is no way to show the meta boxes again unless reload the page

Both Meta Box Conditional Logic and Show Hide:

- Only hide meta boxes via JS, meaning HTML of meta boxes are outputted --> inputs are only hidden, but the meta values are submitted when Save post and are saved in the database
- You can show them without reloading the page

The Meta Box Conditional Logic is differs from Show Hide is: it has more advanced options which allows you to show/hide not only meta boxes but also fields and specific HTML elements. The Show/Hide extension can show/hide only meta boxes. Besides, the conditions in Conditional Logic are more than Show/Hide extension.

Hope that helps :)
