### ISSUE TITLE
Modular Code & API

### ISSUE THREAD

**Issue by ahmadawais** [rilwis/meta-box#741]
I am unable to write modular code for meta boxes with this plugin. Is there an API or can you build one with which I can create classes with singularity principle i.e. one class per field that way single meta box will have as many class as there are fields inside it. 

Right now, it is hard to maintain one big gigantic file with everything inside it.

**Comment by rilwis** [comment]
Hi,

Glad that you stop by :)

The code of the plugin is modular. I refactor the code of the plugin a lot
since version 4.0. In previous versions, everything is put in one file, but
since 4.0, the meta box itself is a class, each field is a class, too. You
can define new class to create a new field easily. Here is the
documentation, please take a look:

https://metabox.io/docs/create-field-type/

If there is anything not clear, please let me know. I will update the docs
with more details.
On Sat, Jan 9, 2016 at 17:41 Ahmad Awais <notifications@github.com> wrote:

> I am unable to write modular code for meta boxes with this plugin Is there
> an API or can you build one with which I can create classes with
> singularity principle ie one class per field that way single meta box will
> have as many class as there are fields inside it
>
> Right now, it is hard to maintain one big gigantic file with everything
> inside it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rilwis/meta-box/issues/741>.
>
-- 
*Tran Ngoc Tuan Anh*
WordPress developer
http://www.deluxeblogtips.com
https://metabox.io
