### ISSUE TITLE
Use current post_id in custom_html or generally using MB?

### ISSUE THREAD

**Issue by lazharichir** [rilwis/meta-box#796]
Hi there,

I have a subscription custom post type and a metabox showing all the charges (custom post type, too) for this subscription

I accept manual payments so I want to add a link (done!) that once clicked, brings me directly to the "Add New Charge" screen and I want to add a GET with the subscription ID to pre-populate the Add New Charge page with pretty much all info bar actualy payment details.

The ID is in the #post_ID hidden field as per WordPress, how can I use it in a custom_html field?

Thanks,

Lazhar

**Comment by rilwis** [comment]
I think you can solve this *partly* with PHP or *fully* with JavaScript.

The problem is: when you creating a **new** post, WP creates a temporary post ID and store in `#post_ID` field. Using PHP code can't get this value as it's not set anywhere yet. If you **have to** get post ID even for new post, then you must use JavaScript. This is a simple code:

```javascript
jQuery( function( $ ) {
    var postId = $( '#post_ID' ).val();
    $( '#where_you_want_to_show_in_custom_html_field' ).text( postId );
} );
```

If you don't need that for new post, only when editing an existing post, then you can get current post Id via `$_GET['post']`
