### ISSUE TITLE
Thickbox Image uploader missing Insert Into Post button in media library tab

### ISSUE THREAD

**Issue by Esager** [rilwis/meta-box#809]
When using the Thickbox Image Uploader for an image field, it's missing the 'Insert Image Into Post' button when you try to select an image from the media library tab.

**Comment by sbouafif** [comment]
The problem seems to come from thickbox which don't show that button when the editor is not available for a post type.

You can force to always show that button by adding this code to functions.php
`add_filter('get_media_item_args', 'allow_img_insertion');
function allow_img_insertion($vars) {
    $vars['send'] = true; // 'send' as in "Send to Editor"
    return($vars);
}`

(it may be fixed by adding this code to the source of this plugin too)

More info here: https://wordpress.stackexchange.com/questions/22175/insert-into-post-button-is-missing-for-certain-images

**Comment by rilwis** [comment]
Thanks @sbouafif for the fix. I've just added it to the plugin.
