### ISSUE TITLE
MetaBox Updater Not updating

### ISSUE THREAD

**Issue by ThomasSultana** [rilwis/meta-box#811]
Hi,

I was having trouble getting the meta box extension plugins to update and realised that you may be calling an incorrect filter. 

Old:
`add_filter( 'pre_set_site_transient_update_plugins', array( $this, 'check_updates' ) );`
New:
`add_filter( 'site_transient_update_plugins', array( $this, 'check_updates' ) );`

Once, i made this change it was able to find the upgrades instantly. Also it would help to put the meta box updater on wordpress.org, to take advantage of update notifications.

This is the reference: https://core.trac.wordpress.org/browser/tags/4.4.2/src/wp-includes/option.php#L1553

**Comment by rilwis** [comment]
Hi, which version are you using? I made an update for the Updater some days ago (v1.1.2) which solves the problem of receiving updates instantly.

The reason `pre_set_site_transient_update_plugins` is used instead of `site_transient_update_plugins` is the 1st filter fires only when WP needs to check for updates, while the later is when WP get the updates (which is checked before). Using the 1st one makes sure the plugin check for update only once.
