### ISSUE TITLE
Google maps on demand

### ISSUE THREAD

**Issue by pixedelic** [rilwis/meta-box#828]
Is there any way to avoid to load maps.google.com/maps/api/js on all pages even if a Google map isn't used? It affects the page speed rank. I'm not here to debut about page rank system, but I would like to show good page rank on my home page at least.

TIA

**Comment by rilwis** [comment]
Hi TIA, do you use the helper function `rwmb_meta` on every page? The plugin loads the script only when the helper function is called for map field.

**Comment by pixedelic** [comment]
Hello, I'm Manuel ('TIA' was for 'thank in advance' :-) ) however, I use `rwmb_meta` to check if the meta box is filled, but I don't use any Google map across the site. When I wrote the message I just installed the site and the only content was the sample page. At this moment I'm using a custom solution instead of your plugin, but if there was a solution I'd be more than glad.

Thank you again

**Comment by rilwis** [comment]
Oh, I see. The `rwmb_meta` if used will trigger the enqueue script for Google maps. Therefore, you will see the script. It was built to help users to output the map in the front end without coding (because it's a *helper*).

If all you need is just a simple check `if ( get_post_meta( get_the_ID(), 'field_id', true ) )`. It's fast and reliable.

So, I think we can close this issue :)

**Comment by pixedelic** [comment]
Ok, thank you!
