### ISSUE TITLE
ThemeCheck Warning: add_shortcode

### ISSUE THREAD

**Issue by PlayerThemes** [rilwis/meta-box#848]
Theme Check WARNING: The theme uses the add_shortcode() function. Custom post-content shortcodes are plugin-territory functionality.

TF soft rejected theme for embedding Meta-Box inside theme which generates above warning.

**Comment by rilwis** [comment]
Hi @PlayerThemes,

The `add_shortcode` should belong to the plugin as that's the plugin territory. The problem is you put everything into your theme and Theme Check will check the **plugin** with the **theme requirements** which cause the problem.

I suggest one of the following solutions:

1. Manually remove the shortcode in the plugin's file. (`inc/functions.php`). But you will need to manually update the code when the plugin is updated. It's not recommended.
2. The better way is using TGM Activation class, which is safer and faster. It makes your theme more lightweight.
