### ISSUE TITLE
'timestamp' => true breaks saving of metabox fields in specific cases

### ISSUE THREAD

**Issue by karissademi** [rilwis/meta-box#849]
Here's the code I'm using to create a datetime metabox.

```
array(
   'name'  => 'Alert Start Time',
   id'    => $prefix . 'alert_start',
   'class' =>  'start-time',
   'type'  => 'datetime',
   'size'  =>  25,
   'js_options' =>  array(
      'timeFormat' =>  'hh:mm tt',
      'dateFormat'=>'mm-dd-yy',
      'stepMinute' => 15,
      'showHour' => 'true',
      'controlType'=> 'select',
      'oneLine'=> true,
      'timeInput' => true,
      ),
   'timestamp' => true
),
```

When the `timestamp` is set to true, the user MUST either use the sliders to select time (or the dropdowns in the above example).

If the user types the date or time, the data doesn't save on publish and will revert back to January 1, 1970 (as seen in https://github.com/rilwis/meta-box/issues/842). The timeInput setting does not appear to have an effect either way, when timestamp is true.

**Comment by d2roth** [comment]
When I had the problem in #842 I found this problem as well.

My research uncovered the following, this is actually an issue with the jQuery plugin that is being used. Well not really an issue just an edge case that gets slightly complicated. Basically there is a hidden input which contains the timestamp, .rwmb-datetime-timestamp, and this is the field that is stored in the database. Now the issue is that the hidden field doesn't get updated unless the "done" button is clicked. This becomes a problem for you and I because when the done button is clicked the currently selected date fills both the visible and hidden fields.

Originally I was thinking that you could simply make the done button check if there was text in the visible field and if not it would set them both blank. This would break the user experience for multiple reasons. Doing some googling it looks like some made a clear button as well as the done button but that doesn't solve the problem when they manually enter a dates

Now that I have written that all out here is what I am thinking might work. Basically add a js handler for when the input loses focus. When it loses focus you would check a, if it is empty and if so set the .rwmb-datetime-timestamp field to blank or b,  if it is not empty parse the date into the timestamp format and update the hidden field. That even could be done server side. On save check if the visible field is empty and if so set the timestamp to false. I can only see an issue when someone manually enters the date as the timestamp would be off. Hmm... What would happen if the timestamp field was only used server-side and would just use strtotime() to get the timestamp instead of requiring js on the front-end.

Anyhow that doesn't answer your question but I hope it helps solving this issue and helps you understand the underlying issue.

**Comment by karissademi** [comment]
Thanks @d2roth. Your response definitely helps shed light on the situation. I'll investigate possible solutions and post back if I come up with anything that seems useful. At least in the short term, we will have to rely on training our users on using the UI elements to update the fields.

**Comment by d2roth** [comment]
@karissademi, have you found anything?

**Comment by karissademi** [comment]
@d2roth This hasn't been a high priority, but hopefully soon!

**Comment by d2roth** [comment]
@karissademi same here. Anyhow last night I got into it a bit and found there are a whole bunch of little catches to it. Like what if someone wants to cancel modifying the date? Like I enter the date with the picker then wipe it out, as soon as I click away my original date is lost but what I really wanted to do was restore the date.

What do you think the flow should be? Do you think it would make sense to simply try and add a "clear" button between "Now" and "Done"? Also with that what about making it so that the default value is blank instead of using false = 0 = January 1, 1970?

I am open to your thoughts/opinions because this is such a great plugin I want to improve it.

**Comment by funkedgeek** [comment]
If you type in the date and time, you have to hit done in the dropdown, otherwise it doesn't get set correctly on save

**Comment by d2roth** [comment]
@funkedgeek Thanks for that fix. It comes a long way but I noticed 2 things when  I tested it. They may be a different issue but seem related. First if you clear the field and then click anywhere else, to update the field you get an error:
> datetime.js?ver=4.8.5:51 Uncaught TypeError: Cannot read property 'getFullYear' of nullgetTimestamp @ datetime.js?ver=4.8.5:51options.onClose @ datetime.js?ver=4.8.5:23overrides.onClose @ jquery-ui-timepicker-addon.min.js?ver=1.5.0:4a.extend._hideDatepicker @ load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,heartbeat,autosave,suggest,wp-ajax-respons…:706a.extend._checkExternalClick @ load-scripts.php?c=1&load[]=hoverIntent,common,admin-bar,heartbeat,autosave,suggest,wp-ajax-respons…:706n.event.dispatch @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.5.2:3r.handle @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.5.2:3

This can be remedied by adding the following to the getTiemstamp( date ) function:
```PHP
if(date===null)
			return "";
```

Secondly with that fix now when you save the post the timestamp reverts back to 0 which ends up being January 1, 1970. This I found could be remedied by only setting the timestamp and formatted keys to $meta if `( $meta != "" )` as follows:
```PHP
	'timestamp' => ( $meta != "" ) ? $meta : null,
	'formatted' => ( $meta != "" ) ? date( call_user_func( $method, $field ), intval( $meta ) ) : "",
```

This solves the problem for me and I hope it finishes up this whole issue.

I am going
