### ISSUE TITLE
fieldset_text within cloneable group

### ISSUE THREAD

**Issue by wgstjf** [rilwis/meta-box#852]
Hi guys,

I need to have a fieldset_text field (or something similar) within a cloneable group...actually in a perfect world I would like to have a cloneable group within a cloneable group but understand this is not a feature yet.

The idea here is that (within the cloneable group) the admin can create a list of items (each with title and description input box) that they can clone to have as many of these items as they need.

The issue is that the cloneable fieldset_text field doesn't save the data correctly, instead of saving the multiple clones of the fieldset_text data it seems to create clones of the parent cloneable item...

Did try a work around by using the 'rows' feature of fieldset_text but this seemed to be ignored.

Any thoughts?

Cheers,

Will

**Comment by wgstjf** [comment]
Hi guys,

Would really appreciate a response on this as I can't figure out a work-around currently and the project is time-sensitive.

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

I'm working on cloned group inside cloned group. So, I will address this issue, too. The bug comes from complicated field `name` attribute which makes the JS run incorrectly. `fieldset_text` is similar to a group as it stores an array of data. So, the same problem. Is it possible for you to move the fieldset_text outside the group in the meantime. Although I'm working on it, but I'm not sure when I can finish.

**Comment by wgstjf** [comment]
Thanks for the reply.  I understand the problem but unfortunately I cannot move the fieldset_text outside the group as it is being used in a form of page builder where the group is a panel on the page.  

Is there a way to get the fieldset_text to show 10 rows and do away with the ability to clone a new row?  For some reason I cannot get it to do so, it just shows 2 whatever I do?

Cheers,

Will

**Comment by rilwis** [comment]
Hi Will,

I've just tested with the latest version of Group and looks like it can handles this situation well. Please check :)
