### ISSUE TITLE
rwmb_meta_boxes called before init

### ISSUE THREAD

**Issue by tomcat90** [rilwis/meta-box#894]
It seems like recently this has changed. We are using get_post_types() to filter out certain posts types for the metaboxes and recently this stopped working because the metaboxes are being called before the init hook that registers the custom posts

**Comment by tomcat90** [comment]
Nevermind. It was a bad call on our part

**Comment by zabestof** [comment]
Hi there,

I have this problem too. What was your workaround?

Cheers!

**Comment by limikael** [comment]
having a problem with this too... specifically, in the init action i'm loading translations, and i want the translations to be available at the time when i'm registering the meta boxes. As a workaround, I'm currently loading the translations using load_plugin_textdomain __before__ any action or anything, but this doesn't seem like the "right" way of doing it.

**Comment by philburton** [comment]
Same here, is there any way to init a function before 'rwmb_meta_boxes'?

**Comment by rilwis** [comment]
Hi guys,

A little note about history: Before version 4.9, the plugin uses `admin_init` hook, which is late enough. But since v4.9, to make the plugin compatible with WPML plugin, we changed to use `init` hook.

Regarding your problem with loading text domain: I can confirm 2 things:

- It's safe to run `load_plugin_textdomain` immediately when loading the plugin files. No hooks is required.
- If you really need a hook, it's **always recommended** to use `plugins_loaded` hook, not the `init`. `plugins_loaded` fires when all plugins are loaded and is safe to load plugin text domain. `init` has a different meaning: initialize something which means the actual work. You should never use it for loading text domain.

**Comment by limikael** [comment]
Thank you @rilwis, that's a very useful and straight to the point advice!
