### ISSUE TITLE
rwmb_show filter question

### ISSUE THREAD

**Issue by fredleput** [rilwis/meta-box#986]
Hi,

Is it possible to do that :

```php
function show_actualites_metabox() {
    global $post;
    // if post is in categorie A show metabox else hide it
}
add_filter(“rwmb_show”, "show_actualites_metabox", $metaboxes["actualites"]);
```

seems that global $post doesn't work

thx

**Comment by rilwis** [comment]
That’s right. The `$post` object is not always available, because the meta box is registered in global scope.

You might want to take a look at [this code](https://github.com/rilwis/meta-box/blob/master/demo/better-include.php) or consider to buy the [Include Exclude](https://metabox.io/plugins/meta-box-include-exclude/) extension.
